services:
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: local_prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    volumes:
      - local_prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  node_exporter:
    privileged: true # butuh ini untuk menandakan bahwa container ini diijinakn untuk mengakses file host
    image: prom/node-exporter
    container_name: local_node_exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume1)($$|/)"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  grafana:
    image: grafana/grafana-oss:10.4.2
    container_name: local_grafana
    restart: always
    env_file:
      - .grafana.env
    volumes:
      - local_grafana_data:/var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  nginx:
    image: nginx:1.25.1
    restart: always
    container_name: local_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        mode: non-blocking

volumes:
  local_prometheus_data:
    name: local_prometheus_data
  local_grafana_data:
    name: local_grafana_data